services:
  postgres:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "lockate"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432

  valkey:
    image: valkey/valkey:8.1.3-alpine
    command: ["valkey-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres_data: