services:
  postgres:
    image: postgres:16-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "lockate"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  redis:
    image: bitnami/redis:8.0.3
    environment:
      REDIS_PASSWORD: "1234"
    restart: unless-stopped

  lockate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3118:3118"
    environment:
      DB_URL: "postgresql://postgres:5432/lockate"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REQUIRE_API_KEY: "${REQUIRE_API_KEY}"

volumes:
  postgres_data: