x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10MB"
      max-file: "10"

services:
  postgres:
    image: postgres:16-bullseye
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "lockate"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    <<: *logging

  valkey:
    image: valkey/valkey:8.1.3-alpine
    command: ["valkey-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
  lockate-api:
    image: lockate:latest
    command: [ "java", "-jar", "lockate.jar", "--spring.profiles.active=api" ]
    restart: unless-stopped
    ports:
      - "3118:3118"
    environment:
      DB_URL: "postgresql://postgres:5432/lockate"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "valkey"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REQUIRE_API_KEY: "${REQUIRE_API_KEY}"
    <<: *logging

  lockate-jobs:
    image: lockate:latest
    command: [ "java", "-jar", "lockate.jar", "--spring.profiles.active=jobs" ]
    restart: unless-stopped
    environment:
      DB_URL: "postgresql://postgres:5432/lockate"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "valkey"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REQUIRE_API_KEY: "${REQUIRE_API_KEY}"
    <<: *logging

  lockate-liquibase:
    image: lockate:latest
    command: [ "java", "-jar", "lockate.jar", "--spring.profiles.active=liquibase" ]
    environment:
      DB_URL: "postgresql://postgres:5432/lockate"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      REDIS_HOST: "valkey"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REQUIRE_API_KEY: "${REQUIRE_API_KEY}"
    <<: *logging

volumes:
  postgres_data:
