spring:
  application:
    name: lockate
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:${DB_URL:postgresql://localhost:5432/lockate}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  security:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:1234}

server:
  port: ${SERVER_PORT:3118}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

lockate:
  require_api_key: ${REQUIRE_API_KEY:true}